### ISSUE TITLE
Final review step has too many records to review

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#148]
We have two options I can think of

- [ ] Narrow the clerical review thresholds (currently between 20% and 80% predicted probability of being a match
- [x] Improve the discriminatory power of the classifier. This really comes down to better features. 
  - [x] Keep casing so USAddress can parse more addresses accurately. #31
  - [x] Store unparsed addressed for training of usaddress #146
  - [x] Pass corpus to text and set fields, #122
  - [x] Name type field #165
  - [ ] Use https://github.com/dirko/pyhacrf when it's ready, https://github.com/datamade/dedupe/issues/14
  - [x] Polynomial expansion of features, https://github.com/datamade/dedupe/issues/373
  - [x] #133
  - [x] #147
