### ISSUE TITLE
Reduce the amount of effort to review.

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#158]
We are working hard to reduce the amount of records that need human review #148, but sometimes there will just be a lot of records to review. 

So, let's optimize our review process for the clerks. 

Some ideas:
- [x] #114 'go back' or 'undo' button for training
- [x] #96 When reviewing, sort the columns left-right by importance
- [x] #162 Speed up filling human review.
- Maybe keyboard shortcuts

@derekeder is going to do some thinking on this, and we'll talk about it together on Monday.
